---

- name: ensure mysql repository
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu trusty universe
    state: present

- name: install mysql if doesn`t exits
  package:
    name: "{{ item }}"
    state: present
  loop:
    - mysql-server-5.7
    - mysql-client-5.7
    - libmysqlclient-dev

- name: ensure mysql-server is running
  service:
    name: mysql
    state: started
    enabled: true

- name: configuring root user pass and priveliges
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_pass }}"
    priv: "*.*:ALL,GRANT"
    login_user: root
    login_password: "{{ mysql_root_pass }}"
  loop:
    - localhost
    - 127.0.0.1
    - ::1
    - "{{ ansible_fqdn }}"

- name: Removes the MySQL test database
  mysql_db:
    db: test
    state: absent
    login_password: "{{ mysql_root_pass }}"
    login_user: root

- name: Deletes anonymous MySQL server user for localhost
  mysql_user:
    user: ""
    state:  absent
    login_password: "{{ mysql_root_pass }}"
    login_user: root