---

- name: install phpmyadmin if doesn`t exits
  package:
    name: "{{ item }}"
    state: present
  loop:
    - phpmyadmin
    - php-mbstring
    - php-gettext

- name: config db settings for phpmyadmin
  template:
   src: phpmyadmin.conf
   dest: /etc/dbconfig-common/phpmyadmin.conf
   owner: root
   group: root
   mode: 0600

#TODO: need to be modified later
- name: running phpenmod commands
  command: "{{ item }}"
  ignore_errors: true
  loop:
    - phpenmod mcrypt
    - phpenmod mbstring